ServerAddress: ":8015"
DatabaseURL: "postgresql://agpt_user:pass123@localhost:5433/agpt_marketplace?connect_timeout=60"
JWTSecret: "Z86RsQ+nhSk+A8ODJX1kQA11JCk9nlw8n+MRdSgmR+P1sMPTTDG1rjBTwj7Ucjb3TRHSVxkCNPgXISmzU/vMkA=="
JWTAlgorithm: "HS256"
CORSAllowOrigins:
  - "http://localhost:3000"
  - "http://127.0.0.1:3000"
