services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=agpt_user
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=agpt_local
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  market:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8015:8015"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8015/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - market

  grafana:
    image: grafana/grafana:latest
    ports:
      - "9091:3000"
    depends_on:
      - prometheus
