# dev values, overwrite base values as needed.

image:
  repository: us-east1-docker.pkg.dev/agpt-dev/agpt-server-dev/agpt-server-dev
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "dev-agpt-server-sa@agpt-dev.iam.gserviceaccount.com"
  name: "dev-agpt-server-sa"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "agpt-dev-agpt-server-ip"
    networking.gke.io/managed-certificates: "autogpt-server-cert"
  hosts:
    - host: server.agpt.co
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

domain: "server.agpt.co"

cloudSqlProxy:
  image:
    repository: gcr.io/cloud-sql-connectors/cloud-sql-proxy
    tag: 2.11.4
  instanceConnectionName: "agpt-dev:us-central1:agpt-server-dev"
  port: 5432
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"

env:
  APP_ENV: "dev"