services:
  postgres-test:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network-test

networks:
     app-network-test:
       driver: bridge
