name: AutoGPT Builder Infra

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/autogpt-infra-ci.yml'
      - 'rnd/infra/**'
  pull_request:
    paths:
      - '.github/workflows/autogpt-infra-ci.yml'
      - 'rnd/infra/**'

defaults:
  run:
    shell: bash
    working-directory: rnd/infra

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: TFLint
        uses: pauloconnor/tflint-action@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tflint_path: terraform/
            tflint_recurse: true
            tflint_changed_only: false

      - name: Debug default branch
        run: echo "Default branch is ${{ github.event.repository.default_branch }}"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: Run chart-testing (lint)
        run: |
          ct lint --target-branch master
